export class RecorderError extends Error {
  constructor(code, message, cause = undefined) {
    super(message);
    this.name = "RecorderError";
    this.code = code;
    this.cause = cause;
  }
}

export const ERROR_CODES = Object.freeze({
  UNSUPPORTED_BROWSER: "UNSUPPORTED_BROWSER",
  BLUETOOTH_PERMISSION: "BLUETOOTH_PERMISSION",
  DEVICE_NOT_SELECTED: "DEVICE_NOT_SELECTED",
  GATT_UNAVAILABLE: "GATT_UNAVAILABLE",
  CHARACTERISTIC_UNAVAILABLE: "CHARACTERISTIC_UNAVAILABLE",
  SUBSCRIPTION_FAILED: "SUBSCRIPTION_FAILED",
  PROTOCOL_UNSUPPORTED: "PROTOCOL_UNSUPPORTED",
  NO_OPTICAL_STREAM: "NO_OPTICAL_STREAM",
  STORAGE_FAILURE: "STORAGE_FAILURE",
  EXPORT_FAILURE: "EXPORT_FAILURE",
  SNIRF_UNAVAILABLE: "SNIRF_UNAVAILABLE"
});
